window:
  startup_mode: Maximized

  font:
    size: 14.0
    use_thin_strokes: true

key_bindings:
  - { key: Equals,   mods: Command, action: IncreaseFontSize }
  - { key: Minus,    mods: Command, action: DecreaseFontSize }
  - { key: V,        mods: Command, action: Paste            }
  - { key: C,        mods: Command, action: Copy             }
  - { key: Paste,                   action: Paste            }
  - { key: Copy,                    action: Copy             }
  - { key: Q,        mods: Command, action: Quit             }
  - { key: W,        mods: Command, action: Quit             }

# Nord Theme
colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
  cursor:
    text: '0x2E3440'
    cursor: '0xD8DEE9'
  normal:
    black: '0x3B4252'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x88C0D0'
    white: '0xE5E9F0'
  bright:
    black: '0x4C566A'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x8FBCBB'
    white: '0xECEFF4'
